### ISSUE TITLE
[Post] May developments by the Ark community

### ISSUE THREAD

**Issue by air1one** [air1one/air1one.github.io#1]
General idea : review the cool PRs merged in the month.

Describe them clearly, show with screenshots.

Would be nice to have the developers select their top 2-3 PRs.

See : 
https://github.com/air1one/air1one.github.io/blob/post-may-devs/_posts/2018-05-31-may-developments.md

**Comment by air1one** [comment]
Hey @dated @ItsANameToo @sharkdev-j I know you contributed a lot to the Ark repositories this month !

I'm trying here to create a blog post (for my website air1.me) to review some cool PRs for this month.
Could you select from your PRs the top 2-3 you think would be nice to share ?

If not, don't worry I can check and select myself but I think it's better to ask to the devs.

Thanks 😃

**Comment by dated** [comment]
Hey there, cool idea, thanks for reaching out! I did mostly UI/UX fixes, let's see if i can find something worthwhile :)

**Comment by dated** [comment]
* ArkEcosystem/ark-explorer#157
* ArkEcosystem/ark-explorer#183 / ArkEcosystem/ark-explorer#226
* ArkEcosystem/ark-mobile#155

i guess the changes to the footer and the link-wallet component have had the biggest impact on the ux - the rest is mostly aesthetics.

**Comment by air1one** [comment]
Nice @dated thanks a lot ! Will include it in the post, I'll show you once it's ready 👍

**Comment by air1one** [comment]
Looking good so far ! https://github.com/air1one/air1one.github.io/blob/post-may-devs/_posts/2018-05-31-may-developments.md

I'm done for today, will continue later 😅

**Comment by ItsANameToo** [comment]
I think these would be the top PRs for me this month:

* ArkEcosystem/ark-explorer#180
* ArkEcosystem/ark-explorer#146 / ArkEcosystem/ark-explorer#218 Both color stuff
* ArkEcosystem/ark-explorer#178

Cool idea with the blog post! :)

**Comment by air1one** [comment]
Thanks @ItsANameToo ! I updated the post : 
https://github.com/air1one/air1one.github.io/blob/post-may-devs/_posts/2018-05-31-may-developments.md

Almost done, waiting a bit for @sharkdev-j to see if he agrees with my ark-net picks. And I will add ark-client.

**Comment by air1one** [comment]
1st version finished : 
https://github.com/air1one/air1one.github.io/blob/post-may-devs/_posts/2018-05-31-may-developments.md

I think I will release it on Monday 👍 

Hey @wownmedia tagging you so you can see this future blog post, as I mentioned 2 of your devs on ark-client. Looking good to you ?

**Comment by CryptologySAC** [comment]
cool! thank you for the mentions.
